# input fastq files
read1:
    JS1: /data/gc-core/taz2008/Pipelines/DNAseq/GRCF_WES/data/fastq/JS1_WES_S1_L000_R1_001.fastq.gz
    JS2: /data/gc-core/taz2008/Pipelines/DNAseq/GRCF_WES/data/fastq/JS2_WES_S2_L000_R1_001.fastq.gz
    JS3: /data/gc-core/taz2008/Pipelines/DNAseq/GRCF_WES/data/fastq/JS3_WES_S3_L000_R1_001.fastq.gz
read2:
    JS1: /data/gc-core/taz2008/Pipelines/DNAseq/GRCF_WES/data/fastq/JS1_WES_S1_L000_R2_001.fastq.gz
    JS2: /data/gc-core/taz2008/Pipelines/DNAseq/GRCF_WES/data/fastq/JS2_WES_S2_L000_R2_001.fastq.gz
    JS3: /data/gc-core/taz2008/Pipelines/DNAseq/GRCF_WES/data/fastq/JS3_WES_S3_L000_R2_001.fastq.gz

# project name (use to nameoutput folder)
project: 'Formenti-JS-12991_220927'

# tumor-normal pairing information
pair:
    JS: ['JS2','JS1']
    Origin: ['JS2','JS3']

# normal samples
normal: ['JS2']

# target bed file
bed: source/bed/EXaCT-2/hg38/exact2.target.liftover.bed
#bed: source/bed/test.bed
cleanbed: source/bed/EXaCT-2/hg38/exact2.target.liftover.cleaned.bed

# cutadapt parameters
overlap: 3
errate: 0.1
minlen: 50
qscore: 10
adapter3: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adapter5: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

# BWA parameters
#bwaidx: /data/gc-core/database/Refs/Homo_sapiens/Ensembl/GRCh38/Sequence/BWAIndex/GRCh38
bwaidx: /data/gc-core/yit2001/Refs/Homo_sapiens/UCSC/hg38/Sequence/BWA_index/Homo_sapiens_assembly38.fasta

# Picard parameters
#refdict: /data/gc-core/database/Refs/Homo_sapiens/Ensembl/GRCh38/Sequence/WholeGenomeFasta/genome.dict
refdict: /data/gc-core/yit2001/Refs/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.dict

# genome assembly
refver: hg38

# GATK
# dbsnp
snpdb: /data/gc-core/yit2001/Refs/Homo_sapiens/UCSC/hg38/resource/Homo_sapiens_assembly38.dbsnp138.vcf

#refseq: /data/gc-core/database/Refs/Homo_sapiens/Ensembl/GRCh38/Sequence/WholeGenomeFasta/genome.fa
refseq: /data/gc-core/yit2001/Refs/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta

# AF only gnomad
gnomad: /data/gc-core/yit2001/Refs/Homo_sapiens/UCSC/hg38/resource/af-only-gnomad.hg38.vcf.gz

# small exac common
exac: /data/gc-core/yit2001/Refs/Homo_sapiens/UCSC/hg38/resource/small_exac_common_3.hg38.vcf.gz

# funcotator data sources path
funco: /data/gc-core/yit2001/Refs/Homo_sapiens/UCSC/hg38/resource/funcotator_dataSources.v1.7.20200521s/

# MAF remove filtered variants?
mafilt: True
#mafilt: False

# MAF columns to write
cols: ['Hugo_Symbol','Entrez_Gene_Id','Center','NCBI_Build','Chromosome','Start_Position','End_Position','Strand','Variant_Classification','Variant_Type','Reference_Allele','Tumor_Seq_Allele1','Tumor_Seq_Allele2','AS_FilterStatus','dbSNP_RS','dbSNP_Val_Status','Tumor_Sample_Barcode','Matched_Norm_Sample_Barcode','Genome_Change','Annotation_Transcript','Transcript_Strand','Transcript_Exon','Transcript_Position','cDNA_Change','Codon_Change','Protein_Change','Other_Transcripts','Refseq_mRNA_Id','Refseq_prot_Id','SwissProt_acc_Id','SwissProt_entry_Id','Description','GO_Biological_Process','GO_Cellular_Component','GO_Molecular_Function','COSMIC_overlapping_mutations','COSMIC_fusion_genes','COSMIC_tissue_types_affected','COSMIC_total_alterations_in_gene','DrugBank','ref_context','gc_content','tumor_f','t_alt_count','t_ref_count','n_alt_count','n_ref_count']

# MAF rename columns if needed
newcols: []

# MAF freeze panes
mrow: 1
mcol: 14

# per-base coverage report
# %>?X
covstart: 0
covend: 150
covstep: 10
# cutoff for low-coverage
lowcut: 10

# target enrichment
# plot size (cm)
plotwidth: 40
plotheight: 20

